Come.Web.Sample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Come.Web.Sample.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Come.Web.Sample/Controllers/OAuth2Controller.cs
using Come.CollectiveOAuth.Models;
using Come.CollectiveOAuth.Utils;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Come.Web.Sample.Controllers
{
    public class OAuth2Controller : Controller
    {

        /// <summary>
        /// 构建授权Url方法
        /// </summary>
        /// <param name="authSource"></param>
        /// <returns>RedirectUrl</returns>
        public ActionResult Authorization(string authSource)
        {
            AuthRequestFactory authRequest = new AuthRequestFactory();
            var request = authRequest.getRequest(authSource);
            var authorize = request.authorize(AuthStateUtils.createState());
            Console.WriteLine(authorize);
            return Redirect(authorize);
        }

        /// <summary>
        /// 授权回调方法
        /// </summary>
        /// <param name="authSource"></param>
        /// <param name="authCallback"></param>
        /// <returns></returns>
        public ActionResult Callback(string authSource, AuthCallback authCallback)
        {
            AuthRequestFactory authRequest = new AuthRequestFactory();
            var request = authRequest.getRequest(authSource);
            var authResponse = request.login(authCallback);
            return Content(JsonConvert.SerializeObject(authResponse));
        }

        /// <summary>
        /// 钉钉callback
        /// </summary>
        /// <param name="authSource"></param>
        /// <param name="authCallback"></param>
        /// <returns></returns>
        public ActionResult DingTalkCallback(AuthCallback authCallback)
        {
            AuthRequestFactory authRequest = new AuthRequestFactory();
            var request = authRequest.getRequest("DINGTALK_SCAN");
            var authResponse = request.login(authCallback);
            return Content(JsonConvert.SerializeObject(authResponse));
        }


        /// Eleme验证授权
        /// </summary>
        /// <param name="authSource"></param>
        /// <param name="authCallback"></param>
        /// <returns></returns>
        public ActionResult ElemeVerification()
        {
            var retMsg = new
            {
                message = "ok"
            };
            return Json(retMsg, JsonRequestBehavior.AllowGet);
        }
    }
}

Come.Web.Sample/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Come.Web.Sample/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Come.Web.Sample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "CollectiveOAuth授权演示";
}

<style>
    .btn-lg, .btn-group-lg > .btn {
        margin-bottom: 13px;
    }
</style>
<div class="jumbotron">
    <p>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "WECHAT_MP"})" class="btn btn-primary btn-lg">
            微信公众号
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "WECHAT_OPEN"})" class="btn btn-primary btn-lg">
            微信开放平台
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "WECHAT_ENTERPRISE"})" class="btn btn-primary btn-lg">
            企业微信静默
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "WECHAT_ENTERPRISE_SCAN"})" class="btn btn-primary btn-lg">
            企业微信扫码
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "ALIPAY_MP"})" class="btn btn-primary btn-lg">
            支付宝服务窗
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "GITEE"})" class="btn btn-primary btn-lg">
            Gitee
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "GITHUB"})" class="btn btn-primary btn-lg">
            Github
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "BAIDU"})" class="btn btn-primary btn-lg">
            百度开放平台
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "XIAOMI"})" class="btn btn-primary btn-lg">
            小米开放平台
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "DINGTALK_SCAN"})" class="btn btn-primary btn-lg">
            钉钉扫码
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "OSCHINA"})" class="btn btn-primary btn-lg">
            Oschina开源中国
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "CODING"})" class="btn btn-primary btn-lg">
            Coding(扣钉)
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "LINKEDIN"})" class="btn btn-primary btn-lg">
            Linkin(领英)
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "WEIBO"})" class="btn btn-primary btn-lg">
            微博
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "QQ"})" class="btn btn-primary btn-lg">
            QQ
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "DOUYIN"})" class="btn btn-primary btn-lg">
            抖音
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "GOOGLE"})" class="btn btn-primary btn-lg">
            Google谷歌
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "FACEBOOK"})" class="btn btn-primary btn-lg">
            Facebook
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "MICROSOFT"})" class="btn btn-primary btn-lg">
            微软
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "TOUTIAO"})" class="btn btn-primary btn-lg">
            今日头条
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "TEAMBITION"})" class="btn btn-primary btn-lg">
            Teambition
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "RENREN"})" class="btn btn-primary btn-lg">
            人人网
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "PINTEREST"})" class="btn btn-primary btn-lg">
            Pinterest
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "STACK_OVERFLOW"})" class="btn btn-primary btn-lg">
            Stack Overflow
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "HUAWEI"})" class="btn btn-primary btn-lg">
            华为
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "KUJIALE"})" class="btn btn-primary btn-lg">
            酷家乐
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "GITLAB"})" class="btn btn-primary btn-lg">
            Gitlab
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "MEITUAN"})" class="btn btn-primary btn-lg">
            美团
        </a>
        <a href="@Url.Action("Authorization", "OAuth2", new {authSource = "ELEME"})" class="btn btn-primary btn-lg">
            饿了么
        </a>

    </p>
</div>

Come.Web.Sample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CollectiveOAuth授权演示", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="https://codoc.rthinkingsoft.cn/guide/introduction.html" target="_blank">使用文档</a></li>
                    <li><a href="https://rthinkingsoft.com" target="_blank">精品源码</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @ViewBag.Title</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>